[package]
name = "bight_nvim"
version = "0.1.3-a"
edition = "2024"

[lib]
name = "bight"
crate-type = ["cdylib"]

[dependencies]
nvim-oxi = {version = "0.6", features = ["neovim-0-11", "test", "mlua"]}
bight = { path = "../bight/bight/" , version = "0.1.1" }
hashbrown = "0.15"
anyhow = "1.0.100"
